resources:
  - name: Jak0ps
    type: GitRepo
    configuration:
      gitProvider: Jak0ps               # Change to your integration
      path: Jak0ps/hello-changes                 # Change to your repo

pipelines:
  - name: pp_testing_123
    steps:
      - name: Pipelines_test
        type: Bash
        configuration:
          environmentVariables:
            test: "123"
          inputResources: 
            - name: Jak0ps
          integrations:
            - name: Jak0ps
        execution:
          onExecute:
            - df -h
            - echo $test
