resources:
  - name: hello_changes_a_git_repo
    type: GitRepo
    configuration:
      path: ~bens/hello-changes
      gitProvider: bsBitbucket
      branches:
        include: master
      files:
        include: \ba[A-Za-z/\.]+\b
  - name: hello_changes_b_git_repo
    type: GitRepo
    configuration:
      path: ~bens/hello-changes
      gitProvider: bsBitbucket
      branches:
        include: master
      files:
        include: \ba[A-Za-z]+\b
pipelines:
  - name: pipeline_a
    configuration:
      environmentVariables:
        readOnly:
          rtRegistry: "pipelines-docker"
          versionTag: "master"
          dockerRepo: "pipelines-docker.jfrog.io/jfrog"
    steps:
      - name: runA
        type: Bash
        configuration:
          inputResources:
            - name: hello_changes_a_git_repo
        execution:
          onStart:
            - pushd a
            - cat boom.sh
            - pop
      # - name: runB
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: hello_changes_b_git_repo
      #   execution:
      #     onStart:
      #       - cat boom.sh
