resources:
  - name: hello_changes_a_git_repo
    type: GitRepo
    configuration:
      path: ~bens/hello-changes
      gitProvider: bsBitbucket
      branches:
        include: master
      files:
        include: \ba\/base\/[A-Za-z/\.]+\b
  - name: hello_changes_version_git_repo
    type: GitRepo
    configuration:
      path: ~bens/hello-changes
      gitProvider: bsBitbucket
      branches:
        include: master
      files:
        include: \ba\/version\/[A-Za-z/\.]+\b
  - name: hello_changes_b_git_repo
    type: GitRepo
    configuration:
      path: ~bens/hello-changes
      gitProvider: bsBitbucket
      branches:
        include: master
      files:
        include: \bb\/version\/[A-Za-z/\.]+\b

pipelines:
  - name: pipeline_a
    configuration:
      environmentVariables:
        readOnly:
          rtRegistry: "pipelines-docker"
          versionTag: "master"
          dockerRepo: "pipelines-docker.jfrog.io/jfrog"
    steps:
      - name: runA
        type: Bash
        configuration:
          inputResources:
            - name: hello_changes_a_git_repo
        execution:
          onStart:
            - cd $res_hello_changes_a_git_repo_resourcePath
            - ls
      - name: runB
        type: Bash
        configuration:
          inputResources:
            - name: hello_changes_version_git_repo
          inputSteps:
            - name: runA
        execution:
          onStart:
            - pushd $res_hello_changes_version_git_repo_resourcePath
            - ls
            - cat a/version/bam.sh
            - popd
