resources:
  - name: hello_changes_git_repo
    type: GitRepo
    configuration:
      path: ~bens/hello-changes
      gitProvider: bsBitbucket
      branches:
        include: master
pipelines:
  - name: find_changes
    configuration:
      environmentVariables:
        readOnly:
          rtRegistry: "pipelines-docker"
          versionTag: "master"
          dockerRepo: "pipelines-docker.jfrog.io/jfrog"
    steps:
      - name: debug
        type: Bash
        configuration:
          inputResources:
            - name: hello_changes_git_repo
        execution:
          onStart:
            - env
      - name: runA
        type: Bash
        configuration:
          inputResources:
            - name: hello_changes_git_repo
              trigger: false
        execution:
          onStart:
            - cat boom.sh
